USE GDSGoods;
DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee (
  szEmpID     VARCHAR(45) NOT NULL,
  szUsername  VARCHAR(45) NOT NULL,
  iManager    VARCHAR(45) NOT NULL DEFAULT 0,
  szFirstName VARCHAR(45) NOT NULL DEFAULT 'Bill',
  szLastName  VARCHAR(45) NULL     DEFAULT 'Nye',
  PRIMARY KEY (szEmpID)
);